export const SET_CODE = "SET_CODE";
export type SET_CODE = typeof SET_CODE;

export const SET_API_LOADING_STATE = "SET_API_LOADING_STATE";
export type SET_API_LOADING_STATE = typeof SET_API_LOADING_STATE;

export const REFRESH_SOURCEFILE = "REFRESH_SOURCEFILE";
export type REFRESH_SOURCEFILE = typeof REFRESH_SOURCEFILE;

export const SET_SELECTED_NODE = "SET_SELECTED_NODE";
export type SET_SELECTED_NODE = typeof SET_SELECTED_NODE;

export const SET_OPTIONS = "SET_OPTIONS";
export type SET_OPTIONS = typeof SET_OPTIONS;

export const OS_THEME_CHANGE = "OS_THEME_CHANGE";
export type OS_THEME_CHANGE = typeof OS_THEME_CHANGE;
